version: '3.9'

services:
  db:
    image: postgres:17.0-alpine3.20
    restart: always
    env_file:
      - ./env_vars/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge
